### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by rjcorwin** [JonathanUsername/terminal_game#2]
Hi there. Cool concept :). I tried it on two different systems with no luck. Both running node 4.2.2 that the README recommends.

```
 λ npm install -g nplaym
-
> child_pty@3.0.1 install /Users/rsteinert/.nvm/versions/node/v4.2.2/lib/node_modules/nplaym/node_modules/child_pty
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Users/rsteinert/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:121:14)
gyp ERR! stack     at /Users/rsteinert/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:110:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:469:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Users/rsteinert/.nvm/versions/node/v4.2.2/bin/node" "/Users/rsteinert/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rsteinert/.nvm/versions/node/v4.2.2/lib/node_modules/nplaym/node_modules/child_pty
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/rsteinert/.nvm/versions/node/v4.2.2/bin/node" "/Users/rsteinert/.nvm/versions/node/v4.2.2/bin/npm" "install" "-g" "nplaym"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! child_pty@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the child_pty@3.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the child_pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls child_pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rsteinert/Github/ICTatRTI/Tangerine-Hub/npm-debug.log
```

```
root@frank:~# npm install -g nplaym
\
> child_pty@3.0.1 install /root/.nvm/versions/node/v4.2.2/lib/node_modules/nplaym/node_modules/child_pty
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/root/.nvm/versions/node/v4.2.2/bin/node" "/root/.nvm/versions/node/v4.2.2/bin/npm" "install" "-g" "nplaym"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! child_pty@3.0.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the child_pty@3.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the child_pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls child_pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
```

**Comment by IngwiePhoenix** [comment]
Install a better python... NodeGYP should have an environment variable that allows you to select a different python interpreter. This is unfortunate, but NodeGYP operates on Google's GYP, which is python based.
