### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by sameerkhoja** [JonathanUsername/terminal_game#3]
Hi! I'd love to try out nplaym, but I receive an error when installing. I am running Node v5.8.0. Here's what I tried on Terminal:

```
Sameers-MBP:~ Sameer$ npm install -g nplaym
/usr/local/bin/nplaym -> /usr/local/lib/node_modules/nplaym/bin/nplaym
/usr/local/lib
└── nplaym@1.3.7 

Sameers-MBP:~ Sameer$ mkdir myProject
Sameers-MBP:~ Sameer$ cd myProject/
Sameers-MBP:myProject Sameer$ nplaym install
module.js:440
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 47, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nplaym/node_modules/child_pty/lib/child_pty.js:1:73)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

Thanks! :smile:

**Comment by JonathanUsername** [comment]
Hey! That's puzzling.. 
My first thought would be to check that it's getting the correct version of node from `/usr/bin/env`. What do you get if you run `/usr/bin/env node --version`? v5.8.0? Does it work if you run it with node directly, like: `node $(which nplaym) install`?

Also, I should correct the docs, but you'll need some packages to install, so make sure your myProject/ dir has a package.json with lots of packages, or else install some directly like `nplaym install babel react redux lodash`.

**Comment by sameerkhoja** [comment]
When I run `/usr/bin/env node --version` I get v5.8.0. I tried the above commands, but I still get the same error. Simply running `nplaym` gives me the same error. Not sure what the issue is, but I'll keep looking into it.
